# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KcAgent < Formula
  desc "Local agent for KubeStellar Console - bridges browser to kubeconfig and Claude Code"
  homepage "https://github.com/kubestellar/console"
  version "0.3.30-nightly.20260604"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/console/releases/download/v0.3.30-nightly.20260604/kc-agent_0.3.30-nightly.20260604_darwin_amd64.tar.gz"
      sha256 "fb34a4c1b155a6b3079cbebc40b4c5feb6a478da8d30f40571732884e8c3bdae"

      define_method(:install) do
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/console/releases/download/v0.3.30-nightly.20260604/kc-agent_0.3.30-nightly.20260604_darwin_arm64.tar.gz"
      sha256 "100692d575aeaebdea966b24014da9cf73a0b15dc3239833e49a4696c94f8208"

      define_method(:install) do
        bin.install "kc-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.30-nightly.20260604/kc-agent_0.3.30-nightly.20260604_linux_amd64.tar.gz"
      sha256 "3366077651086a70455c05fdbd32bf6253ac4bc45c9bc22ef1a578f055241418"
      define_method(:install) do
        bin.install "kc-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/console/releases/download/v0.3.30-nightly.20260604/kc-agent_0.3.30-nightly.20260604_linux_arm64.tar.gz"
      sha256 "1b2d1fd94d8b7ae6c5f06af45a631f3cb733839075ee681c4f8a02a49a5859c4"
      define_method(:install) do
        bin.install "kc-agent"
      end
    end
  end

  test do
    system "#{bin}/kc-agent", "--version"
  end
end
