# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarOps < Formula
  desc "Multi-cluster Kubernetes diagnostics, RBAC analysis, and security checks"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.8.22-nightly.20260603"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.22-nightly.20260603/kubestellar-ops_0.8.22-nightly.20260603_darwin_amd64.tar.gz"
      sha256 "ccfcfb2f78cb33ec0b404fa66f4ce2a39682fb908378496bad1a3d44a8a5a7f1"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.22-nightly.20260603/kubestellar-ops_0.8.22-nightly.20260603_darwin_arm64.tar.gz"
      sha256 "7cf48fdc86728739bf3f7ade6a77357d4ccaec6ee14a30efbf9ace30a216f9a7"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.22-nightly.20260603/kubestellar-ops_0.8.22-nightly.20260603_linux_amd64.tar.gz"
      sha256 "4d52c03e8cb723ceaef79cd62350966809f535ae9d00daf3de32c0cdf9cb407a"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.22-nightly.20260603/kubestellar-ops_0.8.22-nightly.20260603_linux_arm64.tar.gz"
      sha256 "b91cb07d97907c16ca652c8dd7b73a5772e26ad69f9fa483533f6de27e24d585"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  test do
    system "#{bin}/kubestellar-ops", "version"
  end
end
