# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.8.19-nightly.20260515"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.19-nightly.20260515/kubestellar-deploy_0.8.19-nightly.20260515_darwin_amd64.tar.gz"
      sha256 "519c3a6a303a3613fdf11cdd546aa4b11a7e83bac72dadf59cf4205145e98874"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.19-nightly.20260515/kubestellar-deploy_0.8.19-nightly.20260515_darwin_arm64.tar.gz"
      sha256 "f522462363f14a8646574cff234a5435a6c030f61de947805ca6b627a87e9d53"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.19-nightly.20260515/kubestellar-deploy_0.8.19-nightly.20260515_linux_amd64.tar.gz"
      sha256 "cac05a34afa540b78fefb62588d4630ad505e682a8ff9388655666eb10a2ae79"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.8.19-nightly.20260515/kubestellar-deploy_0.8.19-nightly.20260515_linux_arm64.tar.gz"
      sha256 "9488fcf1ce40b0540cc16849d02158c6c4254b34cbecc9477c5adb98e4a3c84b"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  test do
    system "#{bin}/kubestellar-deploy", "version"
  end
end
