# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarOps < Formula
  desc "Multi-cluster Kubernetes diagnostics, RBAC analysis, and security checks"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.9.13-nightly.20260831"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.13-nightly.20260831/kubestellar-ops_0.9.13-nightly.20260831_darwin_amd64.tar.gz"
      sha256 "5d6bb0a3b8be5debdd8b01a3214cb3302b3537843f216864f931e0bf8f5d28ff"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.13-nightly.20260831/kubestellar-ops_0.9.13-nightly.20260831_darwin_arm64.tar.gz"
      sha256 "0bd281ac9aaec1d374deddc65cce63bd6c9e022e6ab78ad6efd070fff492a439"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.13-nightly.20260831/kubestellar-ops_0.9.13-nightly.20260831_linux_amd64.tar.gz"
      sha256 "824379f0421ae2fe3c18c6c7296c9f451114d925cd83e8ba5fad851982aca655"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.13-nightly.20260831/kubestellar-ops_0.9.13-nightly.20260831_linux_arm64.tar.gz"
      sha256 "afac5e0b7c1bfad9f1835626610d3ef0a1bd9446678968ac1fda75d9e405c888"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  test do
    system bin/"kubestellar-ops", "version"
  end
end
