# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarDeploy < Formula
  desc "App-centric multi-cluster deployment and operations for Kubernetes"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.9.9-nightly.20260809"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.9-nightly.20260809/kubestellar-deploy_0.9.9-nightly.20260809_darwin_amd64.tar.gz"
      sha256 "87b1c1f361af2fc49197e912ba7ed7aafa97adf009dc9b0fc1e539cab9a1308c"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.9-nightly.20260809/kubestellar-deploy_0.9.9-nightly.20260809_darwin_arm64.tar.gz"
      sha256 "545588a7d27279c42a6202eb70caad843567a9630fa6f980a97ebc4404197caa"

      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.9-nightly.20260809/kubestellar-deploy_0.9.9-nightly.20260809_linux_amd64.tar.gz"
      sha256 "b70c72cb14f15b577c03fa2193174afdcd4fecdab8e7c17deb2a4675c7a7abf0"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.9-nightly.20260809/kubestellar-deploy_0.9.9-nightly.20260809_linux_arm64.tar.gz"
      sha256 "13e5d2b9b568c40d69c667c81f05b8a7d0c792104048952a7a404a1f8212d18a"
      define_method(:install) do
        bin.install "kubestellar-deploy"
      end
    end
  end

  test do
    system bin/"kubestellar-deploy", "version"
  end
end
