# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubestellarOps < Formula
  desc "Multi-cluster Kubernetes diagnostics, RBAC analysis, and security checks"
  homepage "https://github.com/kubestellar/kubestellar-mcp"
  version "0.9.11-nightly.20260823"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11-nightly.20260823/kubestellar-ops_0.9.11-nightly.20260823_darwin_amd64.tar.gz"
      sha256 "67a30b8e3a076e6d176ccab0400610fc96064149087fb0a4440bcc824e374772"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11-nightly.20260823/kubestellar-ops_0.9.11-nightly.20260823_darwin_arm64.tar.gz"
      sha256 "1869a5e17048eea6bc81bd220c29f155fb122de4892989d95761c91e1f61a7eb"

      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11-nightly.20260823/kubestellar-ops_0.9.11-nightly.20260823_linux_amd64.tar.gz"
      sha256 "8b433341123040fa571985d35646ad30fae121b372a2b1868959197de601e66e"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubestellar/kubestellar-mcp/releases/download/v0.9.11-nightly.20260823/kubestellar-ops_0.9.11-nightly.20260823_linux_arm64.tar.gz"
      sha256 "83f1a34abd1aef5105b8eb8d296052d630c188cc80b69c11f6a2ad32b8e0ae58"
      define_method(:install) do
        bin.install "kubestellar-ops"
      end
    end
  end

  test do
    system bin/"kubestellar-ops", "version"
  end
end
